apiVersion: apps/v1 
kind: Deployment
metadata:
  name: amf-deployment
spec:
  selector:
    matchLabels:
      app: amf
  replicas: 1
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:      
      - name: network-function
        image: free5gc-compose_free5gc-amf
        imagePullPolicy: IfNotPresent
        command: ["./amf"]
        args: ["-amfcfg", "../config/amfcfg.yaml"]
        volumeMounts:
        - name: amfcfg
          mountPath: /free5gc/config/amfcfg.yaml
          subPath: amfcfg.yaml
        env:
        - name: GIN_MODE
          value: release
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.36.2/24", "-g=192.168.36.254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: amfcfg
        configMap:
          name: 5gc-configmap
          items:
          - key: amfcfg.yaml
            path: amfcfg.yaml