apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ausf-deployment
spec:
  selector:
    matchLabels:
      app: ausf
  replicas: 1
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:      
      - name: network-function
        image: free5gc-compose_free5gc-ausf
        imagePullPolicy: IfNotPresent
        command: ["./ausf"]
        args: ["-ausfcfg", "../config/ausfcfg.yaml"]
        volumeMounts:
        - name: ausfcfg
          mountPath: /free5gc/config/ausfcfg.yaml
          subPath: ausfcfg.yaml
        env:
        - name: GIN_MODE
          value: release
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.36.4/24", "-g=192.168.36.254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: ausfcfg
        configMap:
          name: 5gc-configmap
          items:
          - key: ausfcfg.yaml
            path: ausfcfg.yaml

          
      
