apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nssf-deployment
spec:
  selector:
    matchLabels:
      app: nssf
  replicas: 1
  template:
    metadata:
      labels:
        app: nssf
    spec:
      containers:      
      - name: network-function
        image: free5gc-compose_free5gc-nssf
        imagePullPolicy: IfNotPresent
        command: ["./nssf"]
        args: ["-nssfcfg", "../config/nssfcfg.yaml"]
        volumeMounts:
        - name: nssfcfg
          mountPath: /free5gc/config/nssfcfg.yaml
          subPath: nssfcfg.yaml
        env:
        - name: GIN_MODE
          value: release
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.36.6/24", "-g=192.168.36.254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: nssfcfg
        configMap:
          name: 5gc-configmap
          items:
          - key: nssfcfg.yaml
            path: nssfcfg.yaml
      
