apiVersion: apps/v1 
kind: Deployment
metadata:
  name: udr-deployment
spec:
  selector:
    matchLabels:
      app: udr
  replicas: 1
  template:
    metadata:
      labels:
        app: udr
    spec:
      containers:      
      - name: network-function
        image: free5gc-compose_free5gc-udr
        imagePullPolicy: IfNotPresent
        command: ["./udr"]
        args: ["-udrcfg", "../config/udrcfg.yaml"]
        volumeMounts:
        - name: udrcfg
          mountPath:  /free5gc/config/udrcfg.yaml
          subPath: udrcfg.yaml
        env:
        - name: DB_URI
          value: mongodb://db-service:27017
        - name: GIN_MODE
          value: release
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.36.8/24", "-g=192.168.36.254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: udrcfg
        configMap:
          name: 5gc-configmap
          items:
          - key: udrcfg.yaml
            path: udrcfg.yaml
