apiVersion: apps/v1 
kind: Deployment
metadata:
  name: upf1-deployment
spec:
  selector:
    matchLabels:
      app: upf1
  replicas: 1
  template:
    metadata:
      labels:
        app: upf1
    spec:
      containers:      
      - name: network-function
        image: free5gc-compose_free5gc-upf-1
        imagePullPolicy: IfNotPresent
        command: ["./free5gc-upfd"]
        args: ["-f", "../config/upfcfg1.yaml"]
        volumeMounts:
          - name: upfcfg1
            mountPath: /free5gc/config/upfcfg1.yaml 
            subPath: upfcfg1.yaml
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.36.11/24", "-g=192.168.36.254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: upfcfg1
        configMap:
          name: 5gc-configmap
          items:
          - key: upfcfg1.yaml
            path: upfcfg1.yaml
