apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webui-deployment
spec:
  selector:
    matchLabels:
      app: webui
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:      
      - name: frontend
        image: free5gc-compose_free5gc-webui
        imagePullPolicy: IfNotPresent
        command: ["./webui"]
        volumeMounts:
        - name: webuicfg
          mountPath: /free5gc/config/webuicfg.yaml
          subPath: webuicfg.yaml
        env:
        - name: GIN_MODE
          value: release
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: webuicfg
        configMap:
          name: 5gc-configmap
          items:
          - key: webuicfg.yaml
            path: webuicfg.yaml

          
      
