apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
  name: webui-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30000
  selector:
    app: webui