apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: dbdata
  labels:
    5gc: dbdata
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"